apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: replicaset-app
spec:
  replicas: 4
  template:
    metadata:
      name: myapp
      labels:
        app: pod-app
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: pod-app
