name: GitHub Actions Demo

#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, workflow_dispatch]
  # branches:
  #     - 'main'
jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Build Python Project
        uses: pybuilder/build@master
      -
        name: Upload Python Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sampleservice
          path: /home/runner/work/microcicd/microcicd/target/dist/wilo_cloud-1.0.dev0/dist/wilo_cloud-1.0.dev0-py3-none-any.whl
  docker:
    needs: build_artifact
    runs-on: ubuntu-latest
    environment: docker
    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      -  
        name: Download Python Artifact
        uses: actions/download-artifact@v3
        with:
          name: sampleservice
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . 
          #"{{defaultContext}}:src"
          # file: ./Dockerfile
          push: true
          tags: svathsan/flaskcicd:latest
