name: GitHub Actions Demo
on: [push, workflow_dispatch]
jobs:
  python:
     name: Build and Push Python Microservice
     runs-on: ubuntu-latest
     environment: docker
     steps:
         -
           name: Build Python Project
           uses: pybuilder/build@master

         - name: Publish
           env:
             TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
             TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
           run: |
             ls /home/runner/work/microcicd/microcicd/target/dist/
             cd /home/runner/work/microcicd/microcicd/target/dist/*/dist/
             pip install setuptools wheel twine
             twine upload --repository testpypi *

  docker:
    name: Build and Push Docker Image
    needs: python
    runs-on: ubuntu-latest
    environment: docker
    steps:
     -
       name: Checkout
       uses: actions/checkout@v3
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     -
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
     -
       name: Build and push
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: svathsan/hospital_service:4.0.0

  deploy:
    name: Login and Deploy to AWS EKS
    runs-on: ubuntu-latest
    needs: docker
    environment: aws
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: K8 Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          context: .
          args: apply -f deployment.yaml
