name: GitHub Actions Demo

#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]
  # branches:
  #     - 'main'
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: pybuilder/build@master
