name: GitHub Actions Demo

#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, workflow_dispatch]
  # branches:
  #     - 'main'
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      # - 
      #   name: Build Python Project
      #   uses: pybuilder/build@master
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vathsan/flaskcicd:latest
